# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bloques.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from factoreo import Ui_MainWindow


class Ui_BloquesWindow(object):
    def setupUi(self,BloquesWindow):

        BloquesWindow.setObjectName("BloquesWindow")
        BloquesWindow.resize(439,505)
        BloquesWindow.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0.323864, x2:1, y2:0, stop:0 rgba(255, 246, 0, 255), stop:0.482759 rgba(246, 127, 0, 255), stop:1 rgba(255, 0, 132, 255));")
        self.centralwidget = QtWidgets.QWidget(BloquesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0,-10,811,581))
        self.frame.setStyleSheet("\n"
                                 "background-color: rgb(4, 1, 31);\n"
                                 "border-bottom-right-radius: 9px;\n"
                                 "border-bottom-left-radius: 9px;\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60,40,321,391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: white;\n"
                                      "    color: rgb(0, 0, 0);\n"
                                      "    border-radius: 10px;\n"
                                      "    min-width: 10em;\n"
                                      "    padding: 6px;\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(233, 233, 233);\n"
                                      "    color: rgb(251, 251, 251);\n"
                                      "    border-style: inset;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: white;\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "    border-radius: 10px;\n"
                                        "    min-width: 10em;\n"
                                        "    padding: 6px;\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgb(233, 233, 233);\n"
                                        "    color: rgb(251, 251, 251);\n"
                                        "    border-style: inset;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
                                        "    background-color: white;\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "    border-radius: 10px;\n"
                                        "    min-width: 10em;\n"
                                        "    padding: 6px;\n"
                                        "}\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgb(233, 233, 233);\n"
                                        "    color: rgb(251, 251, 251);\n"
                                        "    border-style: inset;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        BloquesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BloquesWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,439,24))
        self.menubar.setObjectName("menubar")
        BloquesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BloquesWindow)
        self.statusbar.setObjectName("statusbar")
        BloquesWindow.setStatusBar(self.statusbar)


        self.retranslateUi(BloquesWindow)
        QtCore.QMetaObject.connectSlotsByName(BloquesWindow)

        self.BloquesWindow = BloquesWindow
        self.pushButton.clicked.connect(self.open_main)

    def open_main(self):
        self.fact = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.fact)
        self.fact.show()
        self.BloquesWindow.hide()

    def retranslateUi(self,MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("BloquesWindow","Bloques"))
        self.pushButton.setText(_translate("BloquesWindow","Bloque 1"))
        self.pushButton_2.setText(_translate("BloquesWindow","Bloque 2"))
        self.pushButton_3.setText(_translate("BloquesWindow","Bloque 3"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    BloquesWindow = QtWidgets.QMainWindow()
    ui = Ui_BloquesWindow()
    ui.setupUi(BloquesWindow)
    BloquesWindow.show()
    sys.exit(app.exec_())
