# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogV2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from bloques import Ui_BloquesWindow
from factoreo import Ui_MainWindow
import time


class Ui_Dialog(object):

        def setupUi(self,Dialog):
                Dialog.setObjectName("Dialog")
                Dialog.resize(402,302)
                Dialog.setStyleSheet("QDialog{\n"
                                     "background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:0, y2:1, stop:0 rgba(239, 61, 160, 255), stop:0.630542 rgba(255, 123, 33, 255), stop:0.926108 rgba(255, 224, 86, 255));\n"
                                     "}")
                self.frame = QtWidgets.QFrame(Dialog)
                self.frame.setEnabled(True)
                self.frame.setGeometry(QtCore.QRect(5,-4,392,301))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
                self.frame.setSizePolicy(sizePolicy)
                self.frame.setAutoFillBackground(False)
                self.frame.setStyleSheet("QFrame{\n"
                                         "background-color: rgb(4, 1, 31);\n"
                                         "border-bottom-right-radius: 9px;\n"
                                         "border-bottom-left-radius: 9px;\n"
                                         "}")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
                self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110,120,171,31))
                self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
                self.horizontalLayout_2.setContentsMargins(0,0,0,0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_2.setFont(font)
                self.radioButton_2.setStyleSheet("color: rgb(242, 242, 243);\n"
                                                 "")
                self.radioButton_2.setChecked(True)
                self.radioButton_2.setObjectName("radioButton_2")
                self.horizontalLayout_2.addWidget(self.radioButton_2,0,QtCore.Qt.AlignHCenter)
                self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.radioButton.setFont(font)
                self.radioButton.setStyleSheet("color: rgb(242, 242, 243);")
                self.radioButton.setObjectName("radioButton")
                self.horizontalLayout_2.addWidget(self.radioButton,0,QtCore.Qt.AlignHCenter)
                self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
                self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240,150,131,144))
                self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
                self.verticalLayout_2.setContentsMargins(0,0,0,0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                spacerItem = QtWidgets.QSpacerItem(20,25,QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Fixed)
                self.verticalLayout_2.addItem(spacerItem)
                self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
                self.pushButton.setObjectName("pushButton")
                self.verticalLayout_2.addWidget(self.pushButton)
                self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
                self.pushButton_2.setObjectName("pushButton_2")
                self.verticalLayout_2.addWidget(self.pushButton_2)
                spacerItem1 = QtWidgets.QSpacerItem(20,30,QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Fixed)
                self.verticalLayout_2.addItem(spacerItem1)
                self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
                self.verticalLayoutWidget.setGeometry(QtCore.QRect(30,150,171,136))
                self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
                self.verticalLayout.setContentsMargins(0,0,0,0)
                self.verticalLayout.setObjectName("verticalLayout")
                spacerItem2 = QtWidgets.QSpacerItem(20,22,QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Fixed)
                self.verticalLayout.addItem(spacerItem2)
                self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
                self.lineEdit.setStyleSheet("border-radius: 5px;")
                self.lineEdit.setInputMask("")
                self.lineEdit.setReadOnly(False)
                self.lineEdit.setClearButtonEnabled(True)
                self.lineEdit.setObjectName("lineEdit")
                self.verticalLayout.addWidget(self.lineEdit)
                self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
                self.lineEdit_2.setStyleSheet("border-radius: 5px;")
                self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
                self.lineEdit_2.setClearButtonEnabled(True)
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.verticalLayout.addWidget(self.lineEdit_2)
                spacerItem3 = QtWidgets.QSpacerItem(20,15,QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Fixed)
                self.verticalLayout.addItem(spacerItem3)
                self.label_3 = QtWidgets.QLabel(self.frame)
                self.label_3.setGeometry(QtCore.QRect(-20,50,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_3.setFont(font)
                self.label_3.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_3.setAlignment(QtCore.Qt.AlignCenter)
                self.label_3.setObjectName("label_3")
                self.frame_2 = QtWidgets.QFrame(self.frame)
                self.frame_2.setGeometry(QtCore.QRect(154,20,85,85))
                self.frame_2.setStyleSheet("QFrame{\n"
                                           "background-color: rgb(242, 242, 242);\n"
                                           "border-radius: 42.4px;\n"
                                           "}")
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setObjectName("frame_2")
                self.label_4 = QtWidgets.QLabel(self.frame_2)
                self.label_4.setGeometry(QtCore.QRect(7,8,70,70))
                self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.frame)
                self.label_5.setGeometry(QtCore.QRect(80,50,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_5.setFont(font)
                self.label_5.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_5.setAlignment(QtCore.Qt.AlignCenter)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.frame)
                self.label_6.setGeometry(QtCore.QRect(60,10,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_6.setFont(font)
                self.label_6.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_6.setAlignment(QtCore.Qt.AlignCenter)
                self.label_6.setObjectName("label_6")
                self.label_7 = QtWidgets.QLabel(self.frame)
                self.label_7.setGeometry(QtCore.QRect(160,30,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_7.setAlignment(QtCore.Qt.AlignCenter)
                self.label_7.setObjectName("label_7")
                self.label_8 = QtWidgets.QLabel(self.frame)
                self.label_8.setGeometry(QtCore.QRect(270,10,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_8.setAlignment(QtCore.Qt.AlignCenter)
                self.label_8.setObjectName("label_8")
                self.label_9 = QtWidgets.QLabel(self.frame)
                self.label_9.setGeometry(QtCore.QRect(10,80,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_9.setFont(font)
                self.label_9.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_9.setAlignment(QtCore.Qt.AlignCenter)
                self.label_9.setObjectName("label_9")
                self.label_10 = QtWidgets.QLabel(self.frame)
                self.label_10.setGeometry(QtCore.QRect(320,40,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_10.setFont(font)
                self.label_10.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_10.setAlignment(QtCore.Qt.AlignCenter)
                self.label_10.setObjectName("label_10")
                self.label_11 = QtWidgets.QLabel(self.frame)
                self.label_11.setGeometry(QtCore.QRect(220,60,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_11.setFont(font)
                self.label_11.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_11.setAlignment(QtCore.Qt.AlignCenter)
                self.label_11.setObjectName("label_11")
                self.label_12 = QtWidgets.QLabel(self.frame)
                self.label_12.setGeometry(QtCore.QRect(307,80,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_12.setFont(font)
                self.label_12.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_12.setAlignment(QtCore.Qt.AlignCenter)
                self.label_12.setObjectName("label_12")
                self.label_13 = QtWidgets.QLabel(self.frame)
                self.label_13.setGeometry(QtCore.QRect(-40,20,131,31))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setItalic(True)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.label_13.setFont(font)
                self.label_13.setStyleSheet("color: rgba(255, 255, 255, 39)")
                self.label_13.setAlignment(QtCore.Qt.AlignCenter)
                self.label_13.setObjectName("label_13")
                self.label_11.raise_()
                self.label_5.raise_()
                self.label_7.raise_()
                self.label_6.raise_()
                self.horizontalLayoutWidget_2.raise_()
                self.verticalLayoutWidget_2.raise_()
                self.verticalLayoutWidget.raise_()
                self.label_3.raise_()
                self.frame_2.raise_()
                self.label_8.raise_()
                self.label_9.raise_()
                self.label_10.raise_()
                self.label_12.raise_()
                self.label_13.raise_()
                self.label_3.setBuddy(self.label_3)
                self.label_5.setBuddy(self.label_3)
                self.label_6.setBuddy(self.label_3)
                self.label_7.setBuddy(self.label_3)
                self.label_8.setBuddy(self.label_3)
                self.label_9.setBuddy(self.label_3)
                self.label_10.setBuddy(self.label_3)
                self.label_11.setBuddy(self.label_3)
                self.label_12.setBuddy(self.label_3)
                self.label_13.setBuddy(self.label_3)

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)
                Dialog.setTabOrder(self.lineEdit,self.radioButton_2)
                Dialog.setTabOrder(self.radioButton_2,self.radioButton)
                Dialog.setTabOrder(self.radioButton,self.lineEdit_2)
                Dialog.setTabOrder(self.lineEdit_2,self.pushButton)
                Dialog.setTabOrder(self.pushButton,self.pushButton_2)

                # CANCEL BUTTON
                self.pushButton_2.clicked.connect(self.cancel_button_clicked)

                # OK BUTTON
                self.pushButton.clicked.connect(self.ok_button_clicked)


        def login(self):
                self.BloquesWindow = QtWidgets.QMainWindow()
                self.ui = Ui_BloquesWindow()
                self.ui.setupUi(self.BloquesWindow)
                self.BloquesWindow.show()
                Dialog.close()

        def clear_user(self):
                self.lineEdit.clear()
                self.lineEdit.setStyleSheet("border-radius: 5px")

        def clear_password(self):
                self.lineEdit_2.clear()
                self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
                self.lineEdit_2.setStyleSheet("border-radius: 5px")

        def ok_button_clicked(self):
                user_text = self.lineEdit.text()
                password_text = self.lineEdit_2.text()

                if user_text and password_text != "":
                        with open("user_data.txt","r") as f:
                                if self.radioButton.isChecked():
                                        users = []
                                        for x in f:
                                                x = x.splitlines()[0].split(":")[0]
                                                users.append(x)
                                        if user_text in users:
                                                  print("Ya existe ese usuario")
                                                  self.lineEdit.setStyleSheet("color: rgb(255, 59, 27);\n"
                                                                              "border-radius: 5px")
                                                  self.lineEdit.setText("Ya existe ese usuario")

                                                  QtCore.QTimer.singleShot(2000, self.clear_user)
                                                  QtCore.QTimer.singleShot(2000, self.clear_password)
                                        else:
                                                with open("user_data.txt", "a") as g:
                                                          g.write(f"\n{user_text}:{password_text}")
                                                g.close()
                                                print("Usuario guardado!")
                                                self.login()

                                else:
                                        users_and_passwords = []
                                        for x in f:
                                                x = x.splitlines()[0]
                                                users_and_passwords.append(x)

                                        if f"{user_text}:{password_text}" in users_and_passwords:
                                                print("logging in")
                                                self.login()

                                        else:
                                                print("Usuario no registrado")
                                                self.lineEdit.setStyleSheet("color: rgb(255, 59, 27);\n"
                                                                            "border-radius: 5px")
                                                self.lineEdit.setText("Usuario no registrado")

                                                QtCore.QTimer.singleShot(2000, self.clear_user)
                        f.close()

                else:
                        if user_text == '':
                                self.lineEdit.setStyleSheet("color: rgb(255, 59, 27);\n"
                                                            "border-radius: 5px")
                                self.lineEdit.setText("Usuario vacío")

                                QtCore.QTimer.singleShot(2000, self.clear_user)

                        if password_text == '':
                                self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
                                self.lineEdit_2.setStyleSheet("color: rgb(255, 59, 27);\n"
                                                            "border-radius: 5px")
                                self.lineEdit_2.setText("Contraseña vacía")
                                QtCore.QTimer.singleShot(2000, self.clear_password)

                        if user_text == '' and password_text == '':
                                self


        def cancel_button_clicked(self):
                Dialog.close()

        def retranslateUi(self,Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate("Dialog","Inicio de Sesión"))
                self.radioButton_2.setText(_translate("Dialog","Log In"))
                self.radioButton.setText(_translate("Dialog","Sign Up"))
                self.pushButton.setText(_translate("Dialog","Ok"))
                self.pushButton_2.setText(_translate("Dialog","Cancel"))
                self.lineEdit.setPlaceholderText(_translate("Dialog","Usuario"))
                self.lineEdit_2.setPlaceholderText(_translate("Dialog","Contraseña"))
                self.label_3.setText(_translate("Dialog","Empresa X"))
                self.label_4.setText(_translate("Dialog",
                                                "<html><head/><body><p><img src=\":/newPrefix/\'RemoveBG Preview 2.png\"/></p></body></html>"))
                self.label_5.setText(_translate("Dialog","Empresa X"))
                self.label_6.setText(_translate("Dialog","Empresa X"))
                self.label_7.setText(_translate("Dialog","Empresa X"))
                self.label_8.setText(_translate("Dialog","Empresa X"))
                self.label_9.setText(_translate("Dialog","Empresa X"))
                self.label_10.setText(_translate("Dialog","Empresa X"))
                self.label_11.setText(_translate("Dialog","Empresa X"))
                self.label_12.setText(_translate("Dialog","Empresa X"))
                self.label_13.setText(_translate("Dialog","Empresa X"))


import images_rc

if __name__ == "__main__":
        import sys

        app = QtWidgets.QApplication(sys.argv)

        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.show()

        sys.exit(app.exec_())
